name: Bug Report
description: Report a bug or issue with S-RCS
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thanks for reporting! Please fill out the form below.

  - type: input
    id: version
    attributes:
      label: S-RCS Version
      placeholder: "e.g., 1.3.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened...
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Screenshots / Videos
      description: Drag and drop screenshots or screen recordings here to help explain the problem.
      placeholder: Paste or drag images/videos here...
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Opera
        - Other
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details (Optional)
      description: Any additional info about your setup
      placeholder: |
        - OS: Windows Server 2022
        - Docker: 24.0.5
        - AD Server: Windows Server 2019
      render: shell
    validations:
      required: false
